apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysecret
  namespace: demo-app
spec:
  encryptedData:
    secret: AgCOcD45cjFAzroZCfHalI8W3n052/aRkWNln0fDtVDR7OHqMxhE00Emd8Hy9h5Dnu+3lPNKc0zOGBGpVHtBRH8tIObtKdYGrF0ungMwLA/69it8jSCTC6erZIGfgQeIfSMwMiQDJlhIObaPTp6Wop73WKReZ4tpzZWiFi6xrerxOR1C22ki76c6I5I9JXeP6yqTicqUZ6RPWVTA0Mh6VV8OHP+aRBVJ1H4QUhXUPy+BsJpAx1TyHZ8KXbWnd0XqSyrgewk76U3iDGziClONepafavohjxZR5Bl3AmcOQKGEGzaiUIdgedKTUS1OAPmfm1hRKPqgvpHxugyb4GOSJK3Dzss1KkLSR0sKYAN/G8S99MCpS0QsK7CLz/OWHl8R2zv6GkuMVRaww24PitzENFrZE5mBTKL6CPAUqm9bz2t+gvMaa5AOfBVodX6ZWTNCzK0DUk8zx6HwqVjhvnUZwb+ZwoUMD+mOwLSNnTsfDypFt3yTM/X+fjGc48p/HGc8tLHif2Df1nJpoUnOvJxnyRAMVyU9lb1fRDb0hFO4rT//01jkHM/T46IoZ2VOhGDtYy5eltnFVMyNWsAdc/V6D4LbbKZHLrGdNoLOsz4yY9xrN6y8b2dL+gRZoJfPcGLrZ7Pf2HQjLaUFNsXo432fly5JX3K9OO5S9qgSqFItNDYjJC+iKSS/FUjJ3F/nkpfsvsxotutPs1oD
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: mysecret
      namespace: demo-app

